httpPort: 13000
metricPort: 5858
appName: game
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://qp-mongo-hs.qp.svc.cluster.local:27017
    userName: root
    password: root123456
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: qp-redis-hs.qp.svc.cluster.local:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7