httpPort: 13000
metricPort: 5856
appName: connector
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://qp-mongo-hs.qp.svc.cluster.local:27017
    userName: root
    password: root123456
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: qp-redis-hs.qp.svc.cluster.local:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs:
    - qp-etcd-hs.qp.svc.cluster.local:2379
  rwTimeout: 3
  dialTimeout: 3
services:
  connector:
    id: connector-1
    clientHost: 0.0.0.0
    clientPort: 12000