metricPort: 5854
appName: user
log:
  level: DEBUG
grpc:
  addr: 0.0.0.0:11500
etcd:
  addrs:
    - qp-etcd3-hs.qp.svc.cluster.local:2379
  register:
    name: user
    addr: user.qp.svc.cluster.local:11500
    version: v1
    weight: 10
    ttl: 10
db:
  mongo:
    url: mongodb://qp-mongo-hs.qp.svc.cluster.local:27017
    userName: root
    password: root123456
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: qp-redis-hs.qp.svc.cluster.local:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7